server:

  port: 6699

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///hotel


  redis:

     port: 6379
     host: localhost


logging:
  level:
    com.lantu: debug

